version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: advisor-backend
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - PYTHONPATH=/app/src
    env_file:
      - .env
    volumes:
      - ./backend/src:/app/src
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - advisor-network

  frontend:
    build:
      context: ./frontend/advisor-frontend
      dockerfile: Dockerfile.frontend
    container_name: advisor-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - advisor-network

networks:
  advisor-network:
    driver: bridge

volumes:
  backend_data:
